### ISSUE TITLE
Switch the FDPClient Source Code to a Better one.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Project-EZ4H/FDPClient#13]
Hi, i wanted to give you guys a better LiquidBounce source code for you guys to improve. Contact me through Guilded, and il send it. It's quite good, maybe you guys can use it as your new base.

**Comment by BobIsMyManager** [comment]
this is based of off liquidbounce, stuff are added fast and the client is already really good.
I don't really think it needs a recode but hey, thats just my opinion

**Comment by gabrielvicenteYT** [comment]
Not a "recode" but simply using another custom liquidbounce base.
