### ISSUE TITLE
Switch the Scaffold to CrossVersion again and fix the Sprint bug on it.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Project-EZ4H/FDPClient#14]
So, i like more the crossversion scaffold, and i would like you guys to switch to it again, but make it sprint if sprint option in scaffold is on.

**Comment by BobIsMyManager** [comment]
I have no idea what you are saying

**Comment by liulihaocai** [comment]
crossversion scaffold is trash

**Comment by liulihaocai** [comment]
i use it before,lot of guys says it is trash so i backword it

**Comment by gabrielvicenteYT** [comment]
The only problem in crossversion scaffold is sprint. It's a bug that can be fixed.
