### ISSUE TITLE
Add autoplay to the source code.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Project-EZ4H/FDPClient#15]
Hi, i want you guys to add autoplay into the source code. I already know that you guys have it in the compiled version, but i want you guys to make it public.

**Comment by BobIsMyManager** [comment]
https://github.com/Project-EZ4H/FDPClient/blob/master/src/main/java/net/ccbluex/liquidbounce/features/module/modules/misc/AutoPlay.kt

**Comment by liulihaocai** [comment]
just in this repo lol
