### ISSUE TITLE
AutoDisable InventoryCleaner while going into a new game.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Project-EZ4H/FDPClient#16]
Hi, i can't use inventorycleaner with autoplay when i want to get into a new game. I know 2 ways to fix this, the first one is better tho.
1st Make InventoryCleaner allow Paper in the hotbar.
2nd Make AutoPlay automatically disable InventoryCleaner when it finds paper and turn it on again in a new game. (Check if InventoryCleaner is enabled so it doesn't turn on for people who don't need InventoryCleaner.)

I honestly think the first option is easier and better overall, but you guys choose.

**Comment by BobIsMyManager** [comment]
1) it's not just paper, in lobbies there are chests, compasses, nether stars and other items
2) this would probably have to apply for chest stealer aswell
3) you can just disable inventory cleaner after the game is done
4) I'm pretty sure auto disable is configurable to whatever you want

**Comment by liulihaocai** [comment]
i add a autodisable,if u change world it will autodisable
but u need to add it with this command
.ad inventorycleaner respawn
