### ISSUE TITLE
criticals, killaura

### ISSUE THREAD

**Issue by viluxgt** [Project-EZ4H/FDPClient#17]
redeskysmartground criticals seem to work less, for me idk about others, so yeah i use redeskylowhop. As i said idk if this is only for me or other people aswell. Oh and yeah if you are using killaura vs a hacker (so u use it a long time) it stops working for some reason after a long time only.

**Comment by BobIsMyManager** [comment]
Killaura stops working after a while for all clients on redesky

**Comment by viluxgt** [comment]
thanks for telling me
