### ISSUE TITLE
[REQUEST] MCLEAKS/EASYMC

### ISSUE THREAD

**Issue by NotAnAcountThatIsOnlyUsedForSchool** [Project-EZ4H/FDPClient#19]
I need them for redesky. I dont think it will be hard to implement as the original liquid bounce already had it.

**Comment by BobIsMyManager** [comment]
Redesky is a cracked server, you don’t need it

**Comment by NotAnAcountThatIsOnlyUsedForSchool** [comment]
But I've been playing on some servers (no cracked) and their config is the same as redesky. The servers is small, so free alt generators have unbanned acounts.

**Comment by liulihaocai** [comment]
i think its useless,because mcleaks can use with mc launcher
