### ISSUE TITLE
Hey! May I translate the client to portuguese? 

### ISSUE THREAD

**Issue by Dudufccg** [Project-EZ4H/FDPClient#20]
My name is Dudu, I'm brazillian and my discord is "Dudu#9656" and I did not find any other way to talk to you except by opening an "issue" on github. I can translate this client for you to portuguese if you want, so brazillians (people who essentially play on redesky as redesky is a brazillian server) can use the client too. Add me on discord if you are interested (I will do it for free if u want).
edit: By this I mean that we do other version of the client, on in portuguese and the normal one you can download on http://fdp.liulihaocai.pw/ 
Sorry if I spelled anything wrong here, my writing in english isn't that good but I swear I can translate to portuguese without any grammar errors.

**Comment by liulihaocai** [comment]
ok,with GPLv3 u can fork it and free modify
(but i think most of redesky hackers is chinese lol)

**Comment by Dudufccg** [comment]
> ok,with GPLv3 u can fork it and free modify
> (but i think most of redesky hackers is chinese lol)

I wasn't talking about hackers, but players XD 
On this weekend I will try translating it. It's the first time I do such a thing.
