### ISSUE TITLE
do you have a discord?

### ISSUE THREAD

**Issue by programmer-socks** [Project-EZ4H/FDPClient#27]
title ^^

**Comment by liulihaocai** [comment]
i have one,but i need vpn to use it,so i cant online often

**Comment by MaurinhoBr11** [comment]
Liuli Are you Brazilian?

**Comment by MaurinhoBr11** [comment]
sorry to ask this but I saw in the alt manager only Nick Brasileiro you and not?

**Comment by liulihaocai** [comment]
no,im chinese

**Comment by liulihaocai** [comment]
i get the words from https://app.memrise.com/course/233334/5000-top-portuguese-words-with-audio/

**Comment by MaurinhoBr11** [comment]
Yes thank you i thought you were brazilian haha

**Comment by MaurinhoBr11** [comment]
Liuli fdp client is a rat? (virus)

**Comment by liulihaocai** [comment]
> 六里fdp的客户是老鼠吗？（病毒）

no itz 100% opensource,u can check src for is it a malware lol
