### ISSUE TITLE
Crashing at startup! Error 0

### ISSUE THREAD

**Issue by namide1** [Project-EZ4H/FDPClient#32]
I have only fdp in mods folder

![image](https://user-images.githubusercontent.com/73107146/117638893-9f841e00-b183-11eb-9ea2-f542b197756d.png)

**Comment by gabrielvicenteYT** [comment]
Try adding optifine.

**Comment by Yex29** [comment]
Also try and add patcher It can usually help with these things

**Comment by namide1** [comment]
Still crashing with code 0

**Comment by namide1** [comment]
Ok it's forge fault

**Comment by namide1** [comment]
Ok it was java and launcher issue
