### ISSUE TITLE
v1.2.1 doesn't download at "https://fdp.liulihaocai.pw"

### ISSUE THREAD

**Issue by TheFathfulFish** [Project-EZ4H/FDPClient#36]
when I click download and install the way you should I install V1.2.0, not v1.2.1???? any help

**Comment by TheFathfulFish** [comment]
when I click download and install the way you should I install V1.2.0, not v1.2.1???? any help

**Comment by Kuraikun11** [comment]
I have the same Problem

**Comment by xHideki** [comment]
I too

**Comment by uncoloryfully8** [comment]
same

**Comment by yourfriendoss** [comment]
build it urself lmfao

**Comment by TheFathfulFish** [comment]
> build it urself lmfao

how tho?

**Comment by liulihaocai** [comment]
i forgot to disable jekyll in my pages lol,so it build failed

**Comment by liulihaocai** [comment]
now it can successful download

**Comment by liulihaocai** [comment]
> also the new version (1.2.2) is out so you're stuck even harder

ummm 1.2.2 is under dev
