### ISSUE TITLE
Version Upgrade Error

### ISSUE THREAD

**Issue by ThanhMinecraftVN123** [Project-EZ4H/FDPClient#37]
why when i download the latest version and put it in mods folder but when i play minecraft it's version 1.2.0 ?

**Comment by Kuraikun11** [comment]
same

**Comment by ZeroPointt** [comment]
Me too.

**Comment by NoobMaster420-69** [comment]
me too

**Comment by TheFathfulFish** [comment]
yeah is seems to be a problem atm sadge

**Comment by xHideki** [comment]
same

**Comment by liulihaocai** [comment]
dup with issue (#36)
