### ISSUE TITLE
Open source datei FDPClient problem

### ISSUE THREAD

**Issue by AdminEvil12** [Project-EZ4H/FDPClient#41]
Could not find net.minecraftforge:forgeBin:1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).
Searched in the following locations:
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - https://maven.minecraftforge.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - https://libraries.minecraft.net/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - file:/C:/Users/Name_/.m2/repository/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - file:/C:/Users/Name_/.m2/repository/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - https://repo.maven.apache.org/maven2/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - https://jitpack.io/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - https://jitpack.io/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - https://repo.spongepowered.org/maven/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - https://repo.spongepowered.org/maven/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - file:/C:/Users/Name_/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).pom
  - file:/C:/Users/Name_/.gradle/caches/minecraft/deobfedDeps/net/minecraftforge/forgeBin/1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient)/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - file:/C:/Users/Name_/OneDrive/Desktop/FDPClient-master/.gradle/minecraft/forgeBin-1.8.9-11.15.1.2318-1.8.9-PROJECT(FDPClient).jar
  - file:/C:/Users/Name_/OneDrive/Desktop/FDPClient-master/.gradle/minecraft/forgeBin.jar
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by AcaiBerii** [comment]
I'm assuming there's something wrong with your build,gradle. Maybe remove everything that says (FDPClient) I guess.

There may be a chance that, if you're building with an IDE, there could be something with that too. Maybe even check your JDK.

**Comment by AdminEvil12** [comment]
problem is build.gradle

**Comment by liulihaocai** [comment]
./gradlew setupDecompWorkspace
./gradlew genIntellijRuns
and build again
