### ISSUE TITLE
(suggestion) Astolfo Clickgui or flux (old)

### ISSUE THREAD

**Issue by goztb22** [Project-EZ4H/FDPClient#42]
i have suggestion liike to add diffrent clients guis like flux or astolfo

**Comment by NotAnAcountThatIsOnlyUsedForSchool** [comment]
Its prob getting added because the newclickgui module on the client category

**Comment by goztb22** [comment]
yeahh that would be cool bc we can make astolfo or even flux hud so yea

**Comment by liulihaocai** [comment]
lazy lol
