### ISSUE TITLE
Add spoof & pick AutoBlock modes in scaffold.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Project-EZ4H/FDPClient#45]
Hey, i think this is a "good" idea. Now that this custom lb has a hypixel fly, you and your team should add things like this.
Instead of stayautoblock and autoblock options, this:
AutoBlock: Off, Spoof, Switch, Pick
Now, this is exactly like mems scaffold, and that's what i want to be added.
Spoof is like Pick but SILENT, so it renders as the item you were using.
Switch is the Old AutoBlock on StayAutoBlock on,
Pick just switches what you are holding to a block, then back to the item you were using.
Off is self explanatory.

**Comment by liulihaocai** [comment]
yea, this is a good idea

**Comment by liulihaocai** [comment]
and maybe stayautoblock in scaffold is broken

**Comment by contionability** [comment]
Fixed and added

**Comment by contionability** [comment]
I have already simplified it into a single mode list
