### ISSUE TITLE
Redesky Highjump.

### ISSUE THREAD

**Issue by gabrielvicenteYT** [Project-EZ4H/FDPClient#46]
Hi again, i also want redesky highjump to be added.
Something like this:
https://www.youtube.com/watch?v=1Vr4kFKonOE

**Comment by liulihaocai** [comment]
i'll add it

**Comment by RangelMK** [comment]
please, news clickgui styles https://github.com/lukflug/PanelStudio and add Esp Skeleton, esp player item,
new killaura with switchdelay and blockrange and priority armor breaker for HVH
command .tp (teleport) command
add FullBright AirJump BlockWalk and autoblock modes for Killaura and timer option dependencies in Infinity aura and also do not teleport option and arraylist with space option in module, add NoRender AutoSword
PointerESP and KillESP and CapeCustom & watermaker and icons notifications add a namespoof .nick spoof and show skin and add more shades of colors for example dark in arraylist
