### ISSUE TITLE
I think ModuleInfo is USELESS

### ISSUE THREAD

**Issue by liulihaocai** [Project-EZ4H/FDPClient#64]
idk what can do by this module
but ik u can see active modules in arraylist
should we remove it?

**Comment by RangelMK** [comment]
please add new stuff like eg Killaura Switchdelay, blockrange, autoblock, update Infinity aura for 200 reach and criticals and 20 cps 
add Radar, add AntiFireBall add Norender add new clickgui with icons like astolfo

**Comment by liulihaocai** [comment]
okay
