### ISSUE TITLE
Scaffold flag redesky

### ISSUE THREAD

**Issue by MaurinhoBr11** [Project-EZ4H/FDPClient#92]
Hey, I'm using scaffolding on redesky with sword and I carry flag can you help me?

**Comment by liulihaocai** [comment]
idk,plz send me ur scaffold config

**Comment by MaurinhoBr11** [comment]
I use it from the fdp client site, and when I go to use the blocks it starts to disappear and I fall into void.

**Comment by MaurinhoBr11** [comment]
what do I do?

**Comment by MaurinhoBr11** [comment]
https://prnt.sc/1cfe4cw

**Comment by MaurinhoBr11** [comment]
https://prnt.sc/1cfecmb

**Comment by liulihaocai** [comment]
hmm i never flag when scaffold

**Comment by MaurinhoBr11** [comment]
Ok .....

**Comment by MaurinhoBr11** [comment]
so I must configure the scaffold myself Thank you Liuli
